[package]
name = "herald"
version = "0.1.0"
authors = ["xermicus <bigcyrill@hotmail.com>"]

[dependencies]
telegram-bot = "0.6.1"
futures = "0.1"
tokio-core = "0.1"

[replace]
"openssl:0.9.24" = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }
